import type { Metadata, Viewport } from "next";
import { Toaster } from "sonner";
import { garamond } from "@/lib/fonts";
import "./globals.css";
import "./swiper-styles.css";

export const metadata: Metadata = {
  title: "Quantum Homes",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",   // allows content to extend behind notch / Dynamic Island
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${garamond.className} antialiased w-full`}>
        {children}
        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}
